name: journal
dependencies:
    - setuptools
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - matplotlib
    - ipython
    - jupyter
    - pandas
    - sympy
    - nose
    - pyyaml
    - tensorflow
    - click
    - h5py
    - pip
    - pip:
        - keras
        - nipype
        - nilearn
