name: journal-gpu
channels:
    - defaults
dependencies:
    - python=3
    - setuptools
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - matplotlib
    - ipython
    - jupyter
    - pandas
    - sympy
    - nose
    - pyyaml
    - tensorflow-gpu
    - click
    - h5py
    - pip
    - pip:
        - keras
        - nipype
        - nilearn
